### PR TITLE
ssl support added

### PR DESCRIPTION
**Pull request by azg1966**
SSL support

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Hi @azg1966, thanks for the contribution.

Can you explain the use case for SSL support with the runserver command?

I really can't imagine why someone would need or want to use SSL when running a project locally. (But happy to be proved wong.)

**Comment by azg1966** [comment]
Telegram's bot API needed https://core.telegram.org/bots/api#making-requests

**Comment by samuelcolvin** [comment]
Ok, I'm still not clear why you would want to run the development server and receive real webhooks. 

Surely develop locally with adev with a script copying telegram requests to test, then deploy with gunicorn and test with real webhooks?

If you really want to use adev while testing with real webhooks you could proxy through nginx and do the ssl termination there.

**Comment by samuelcolvin** [comment]
Sorry not to be more positive, just wondering if this is really necessary.

**Pull request closed without merging**
